### ISSUE TITLE
下载后如何安装和配置

### ISSUE THREAD

**Issue by windzhu0514** [go-vgo/Mingw#1]
MingW下载后如何安装和配置

**Comment by vcaesar** [comment]
You only need to set environment variables.

**Comment by windzhu0514** [comment]
下载位置C:\Mingw    PATH环境变量设置了这个路径  demo程序编译提示 
relocation target png_create_write_struct not defined
relocation target png_set_longjmp_fn not defined
等等其他错误 zlib & libpng 需要怎么设置

**Comment by vcaesar** [comment]
Do not configure, direct use, what is your system version and number of bits?

**Comment by windzhu0514** [comment]
windows 64   
当前目录结构
![qq 20170331143354](https://cloud.githubusercontent.com/assets/5474294/24539068/4c31e254-161f-11e7-92e0-059fcd7de3d4.png)

**Comment by vcaesar** [comment]
There is no problem with my Windows 7, png_create_write_struct not defined is the problem with libpng, i try again again clone.

**Comment by windzhu0514** [comment]
你的环境变量是如何设置的？？？

**Comment by vcaesar** [comment]
"C:\Mingw\bin", this kind of problem is recommended to search for learning first.

**Comment by windzhu0514** [comment]
thank you  i will search it
